### ISSUE TITLE
Resolve SMILES and InChI

### ISSUE THREAD

**Issue by cmgrulke** [Chemical-Curation/resolver#11]
**As a** *anyonymous user*
**I want** *to be able to find chemicals by smiles and inchi*
**So that** *I can find the chemicals I am interested in*

`GET https://api.chemreg.epa.gov/search?identifer=$$$$$$$`

The resolver must be able to take in a smiles or inchi, convert it to inchikey and return the correct chemical based on inchikey lookup

**Acceptance Criteria:**
* SMILES and InChI do return the correct hit based on inchikey matching. 
* the score returned is 1.0, the same as for a regular inchikey match (see django#153)

**Comment by jtumkur** [comment]
- Find Smiles in InChi for each chemical.
- Resolver need indigo or indigo conversion capabilities.
-Add filter with Indigo
- 3rd microservice just for Indigo or Smiles ? or build Indigo functionality into Resolver itself
- Inchi key hashed version for Inchi. Connection information is embedded itself
- Inchi consists for structural information
- "?" tried to search will display anything

**Comment by mwfrost** [comment]
*For sprint review*
InChI for Hydrogen Peroxide: http://127.0.0.1:5000/api/v1/resolver?identifier=InChI=1S/H2O2/c1-2/h1-2H

SMILES: http://127.0.0.1:5000/api/v1/resolver?identifier=OO

InChI search for "Sample substance": http://127.0.0.1:5000/api/v1/resolver?identifier=InChI=1S/C22H26FNO2/c1-17-4-8-19(9-5-17)22(26)12-15-24(16-13-22)14-2-3-21(25)18-6-10-20(23)11-7-18/h4-11,26H,2-3,12-16H2,1H3

http://127.0.0.1:5000/api/v1/resolver?identifier=CC1=CC=C(C=C1)C2(CCN(CC2)CCCC(=O)C3=CC=C(C=C3)F)O
