### ISSUE TITLE
Sync Problem

### ISSUE THREAD

**Issue by dmlyons2** [Chemical-Curation/resolver#17]
When I run the sync command inside the django container I get the following error message:

Error:
```bash
root@ec1c7091649b:/app# python manage.py sync
Syncing Substances with Resolver
Clearing substances...
Invalid URL '/api/v1/substances/_index': No schema supplied. Perhaps you meant http:///api/v1/substances/_index?
```
.env file:
```bash
# These are the default settings in the Django application.
#
# A description of each setting can be found here:
# https://github.com/Chemical-Curation/chemcurator_django/wiki/Configuration

CACHE_URL=redis://redis:6379/0
DEBUG=true
SESSION_COOKIE_AGE=900
SECRET_KEY=some_long_secret
URL_CONF=api
WHITELIST_CORS=ccte-chemreg-stg.epa.gov
WHITELIST_HOST=ccte-api-chemreg-stg.epa.gov
WHITELIST_LOCAL=true
WEB_CONCURRENCY=1
ADMIN_BRANCH=staging-release
ADMIN_DOMAIN=ccte-admin-chemreg-stg.epa.gov
ADMIN_SECRET_KEY=HIDDEN
API_BRANCH=staging-release
API_DOMAIN=ccte-api-chemreg-stg.epa.gov
API_SECRET_KEY=HIDDEN
SPA_DOMAIN=ccte-chemreg-stg.epa.gov
SQL_DATABASE=HIDDEN
SQL_HOST=HIDDEN
SQL_PASSWORD=HIDDEN
SQL_PORT=HIDDEN
SQL_USER=HIDDEN
DATABASE_URL=HIDDEN
ALLOWED_HOSTS=HIDDEN
SQL_DATABASE_ADMIN=HIDDEN
```

**Comment by jtumkur** [comment]
Template name - Resolution URL.
Docker compose needs to be edited as per Michael.
 5 different Docker composers.
Edit the docker composer in the Build.
Every docker composer that is built should have a monitoring tool. Template.env will be updated. 
And that template will be updated. Waiting for variable input from Michael to David.

**Comment by michael-barbour** [comment]
There is an `.env` variable `RESOLUTION_URL=`

for me it's `http://127.0.0.1:5000`

This should currently be in the `template.env`

**Comment by dmlyons2** [comment]
@michael-barbour - This `RESOLUTION_URL=` should be in the `chemcuration_django` repo .env -> do I have that correct? It is still giving the following error after rebuild:
```bash
root@4d37204c7bda:/app# python manage.py sync
Syncing Substances with Resolver
Clearing substances...
Invalid URL '/api/v1/substances/_index': No schema supplied. Perhaps you meant http:///api/v1/substances/_index?
````

**Comment by dmlyons2** [comment]
It was the `RESOLUTION_URL=` .env variable not being set in the docker-compose.yml
