### ISSUE TITLE
remove containment search from resolution

### ISSUE THREAD

**Issue by cmgrulke** [Chemical-Curation/resolver#21]
**As a** anonymous user
**I want to** be able to able to retrieve exact matches without them being buried in containment results
**So that** I can find the chemical I am interested in

`GET https://api.chemreg.epa.gov/search?identifer=$$$$$$$`

Current search use containment (I think of it as a SQL "like" search).  At this point, we only need to be retrieving exact matches from the resolution api where the identifier in the request is equal to the identifier in the document (note this should be case-insensitive though)

Acceptance Criteria:
- do not return containment results in the response, only exact matches.

**Comment by mwfrost** [comment]
Case insensitivity is in Resolver ticket #22
