### ISSUE TITLE
Resolution pagination

### ISSUE THREAD

**Issue by cmgrulke** [Chemical-Curation/resolver#23]
**As a** anonymous user
**I want to** receive unpaginated results from the resolver api
**So that** I can find the chemical I am interested in without requesting new pages

`GET https://api.chemreg.epa.gov/search?identifer=$$$$$$$`

When exactly matching identifiers, the number of results are, as a general rule, small.  Pagination is not required and adds complexity that is currently not needed at this endpoint   

Acceptance Criteria:
- requests result in unpaginated responses containing the hits.

**Comment by jtumkur** [comment]
Resolver Api does not show the Url. Only Meta data
